---
# Node.js version to install
nodejs_version: "20.x"

# Common npm packages to install globally
nodejs_global_packages:
  - yarn
  - typescript
  - "@angular/cli"
  - create-react-app
  - nodemon
  - eslint
  - prettier 