---
- name: Include dependencies tasks
  ansible.builtin.include_tasks:
    file: dependencies.yml

- name: Remove existing chezmoi directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/.config/chezmoi"
    - "{{ ansible_env.HOME }}/.local/share/chezmoi"

- name: Create required directories
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  loop:
    - { path: "{{ ansible_env.HOME }}/.local/bin", mode: '0755' }
    - { path: "{{ ansible_env.HOME }}/.config/chezmoi", mode: '0755' }
    - { path: "{{ ansible_env.HOME }}/.local/share/chezmoi", mode: '0755' }

- name: Install chezmoi
  shell: |
    sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "{{ ansible_env.HOME }}/.local/bin"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/chezmoi"
    executable: /bin/bash

- name: Copy chezmoi configuration files
  copy:
    src: "{{ playbook_dir }}/../chezmoi/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: ".chezmoi.toml", dest: "{{ ansible_env.HOME }}/.config/chezmoi/chezmoi.toml" }

- name: Initialize chezmoi
  shell: "{{ ansible_env.HOME }}/.local/bin/chezmoi init"
  args:
    executable: /bin/bash
  register: chezmoi_init

- name: Copy chezmoi source files
  copy:
    src: "{{ playbook_dir }}/../chezmoi/"
    dest: "{{ ansible_env.HOME }}/.local/share/chezmoi"
    mode: preserve
  when: chezmoi_init.rc == 0

- name: Apply chezmoi configuration
  shell: |
    export PATH="$PATH:{{ ansible_env.HOME }}/.local/bin"
    {{ ansible_env.HOME }}/.local/bin/chezmoi apply --force --refresh-externals
  args:
    executable: /bin/bash
  when: chezmoi_init.rc == 0