---
- name: Set Node.js repository key for Debian/Ubuntu
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  when: ansible_os_family == "Debian"
  become: true

- name: Add NodeSource repository for Debian/Ubuntu
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true

- name: Add NodeSource repository for Fedora
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_{{ nodejs_version }} | bash -
  when: ansible_os_family == "RedHat"
  become: true

- name: Install Node.js and npm
  package:
    name: nodejs
    state: present
  become: true

- name: Install global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ nodejs_global_packages }}"
  become: true 